# Generated by Django 4.1.5 on 2023-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='value_per_bitcoin',
            field=models.FloatField(),
        ),
    ]
