# Generated by Django 4.1.5 on 2023-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currencyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='coin',
            field=models.CharField(default='BTC', max_length=255),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='target_currency',
            field=models.CharField(default='USD', max_length=255),
        ),
    ]
