# Generated by Django 4.1.5 on 2023-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_currencyhistory_coin_currencyhistory_target_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json', models.JSONField()),
            ],
        ),
    ]
